"""Sandbox test for agent module.

Validates core schemas: conversation, chat request, tool call, timeline event,
and draft event shapes — without calling real LLM or DB.
"""


def test_chat_request_schema() -> None:
    """Chat request schema contract."""
    req = {
        "conversation_id": 1,
        "content": "Hello, how can you help me?",
        "profile_key": None,
        "resume_checkpoint_id": None,
        "enable_checkpointer": None,
    }
    required = {"conversation_id", "content"}
    for field in required:
        assert field in req, f"Missing required field: {field}"
    assert req["conversation_id"] > 0
    assert req["content"].strip()
    print("  [CHAT] Request schema valid")


def test_conversation_schema() -> None:
    """Conversation shape contract."""
    conv = {
        "id": 1,
        "title": "New conversation",
        "status": "active",
        "created_at": "2026-07-01T00:00:00",
        "updated_at": "2026-07-01T00:00:00",
    }
    required = {"id", "title", "status"}
    for field in required:
        assert field in conv, f"Missing required field: {field}"
    assert conv["status"] in ("active", "archived", "completed"), f"Invalid status: {conv['status']}"
    print("  [CONVERSATION] Shape valid")


def test_tool_call_event_shape() -> None:
    """Tool call event shape contract (sandbox timeline item)."""
    event = {
        "type": "tool_call",
        "tool_name": "knowledge__search",
        "arguments": {"query": "skincare ingredients"},
        "result": {"results": []},
        "timestamp": "2026-07-01T00:00:00",
        "status": "completed",
    }
    required = {"type", "tool_name", "arguments", "status"}
    for field in required:
        assert field in event, f"Missing required field: {field}"
    assert isinstance(event["arguments"], dict)
    assert event["status"] in ("completed", "failed", "pending")
    print("  [TOOL_CALL] Event shape valid")


def test_message_event_shape() -> None:
    """Message event shape contract."""
    event = {
        "type": "message",
        "role": "assistant",
        "content": "Here is some information...",
        "timestamp": "2026-07-01T00:00:00",
    }
    required = {"type", "role", "content"}
    for field in required:
        assert field in event, f"Missing required field: {field}"
    assert event["role"] in ("user", "assistant", "system")
    print("  [MESSAGE] Event shape valid")


def test_draft_event_shape() -> None:
    """Draft event (article draft generated by agent) shape contract."""
    draft = {
        "type": "draft",
        "title": "Generated Article",
        "content": "Full article text...",
        "format": "markdown",
        "timestamp": "2026-07-01T00:00:00",
    }
    required = {"type", "title", "content"}
    for field in required:
        assert field in draft, f"Missing required field: {field}"
    print("  [DRAFT] Event shape valid")


def test_response_shape() -> None:
    """Unified API response shape contract."""
    r = {"success": True, "data": {"conversation_id": 1, "events": []}, "error": None}
    assert all(k in r for k in ("success", "data", "error"))
    assert r["success"] is True
    print("  [RESPONSE] Shape valid")


def main() -> None:
    print("=" * 60)
    print("agent sandbox test")
    print("=" * 60)
    test_chat_request_schema()
    test_conversation_schema()
    test_tool_call_event_shape()
    test_message_event_shape()
    test_draft_event_shape()
    test_response_shape()
    print("=" * 60)
    print("PASS: agent sandbox test")


if __name__ == "__main__":
    main()
