// AUTO-GENERATED FILE — DO NOT EDIT
// Source of truth: products/*/product.json entryComponentKey values
// Generated by frontend/scripts/scan-products.js
import type { Component } from 'vue'

export const productComponentKeyMap: Record<string, () => Promise<{ default: Component }>> = {
  'products/content-studio/frontend/index.vue': () => import('@products/content-studio/frontend/index.vue'),
  'products/office/frontend/index.vue': () => import('@products/office/frontend/index.vue'),
}
