<template>
  <div class="component-registration-error">
    <div class="component-registration-error_icon">!</div>
    <h3 class="component-registration-error_title">App component is not registered</h3>
    <p class="component-registration-error_message">
      The desktop registry points to a component key that was not generated by the module scanner.
    </p>
    <dl class="component-registration-error_meta">
      <div>
        <dt>App</dt>
        <dd>{{ appName || appKey || 'Unknown app' }}</dd>
      </div>
      <div>
        <dt>Component key</dt>
        <dd>{{ componentKey || 'Empty component key' }}</dd>
      </div>
    </dl>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  appKey?: string
  appName?: string
  componentKey?: string
}>()
</script>

<style scoped>
.component-registration-error {
  min-height: 220px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  padding: 28px;
  color: #334155;
  text-align: center;
}
.component-registration-error_icon {
  width: 38px;
  height: 38px;
  border-radius: 999px;
  display: grid;
  place-items: center;
  background: #fef2f2;
  color: #dc2626;
  font-weight: 800;
}
.component-registration-error_title {
  margin: 0;
  font-size: 16px;
  font-weight: 700;
  color: #0f172a;
}
.component-registration-error_message {
  margin: 0;
  max-width: 420px;
  font-size: 13px;
  line-height: 1.6;
  color: #64748b;
}
.component-registration-error_meta {
  margin: 8px 0 0;
  display: grid;
  gap: 8px;
  min-width: min(420px, 100%);
  text-align: left;
}
.component-registration-error_meta div {
  display: grid;
  grid-template-columns: 110px minmax(0, 1fr);
  gap: 12px;
  padding: 8px 10px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  background: #f8fafc;
}
.component-registration-error_meta dt {
  font-size: 12px;
  font-weight: 700;
  color: #64748b;
}
.component-registration-error_meta dd {
  margin: 0;
  min-width: 0;
  overflow-wrap: anywhere;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  font-size: 12px;
  color: #0f172a;
}
</style>
